//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bulding_Vistor_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record
    {
        public int RecordId { get; set; }
        public int VisitorId { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan Time { get; set; }
        public int TenantId { get; set; }
        public int AppartmentId { get; set; }
    
        public virtual Appartment Appartment { get; set; }
        public virtual Tenant Tenant { get; set; }
        public virtual Visitor Visitor { get; set; }
    }
}
